### ISSUE TITLE
No-route doesn't work

### ISSUE THREAD

**Issue by aminvakil** [aminvakil/docker-ocserv#1]
Unfortunately I couldn't make no-route work and all private ips route to ocserv as well.

Any ideas?

**Comment by aminvakil** [comment]
It seems that it's up to clients whether they follow routes given by server or not, so it does work indeed.

**Comment by carmineyiu** [comment]
no-route does not work. the following is the error that display in anyconnect client. "The VPN client was unable to successfully verify the IP forwarding table modifications.  A VPN connection will not be established." error. 

If I remember correctly, anyconnect client does not support OCSERV server for no-route feature, the only option is either 1) delete the no-route or 2) use openconnect client

**Comment by aminvakil** [comment]
@carmineyiu Thanks for the information, I didn't know that.
But from experience with different clients on android, different linux distros with different versions of networkmanager and running different versions of openconnect directly from terminal and windows, I realized that it's up to clients whether they respect `no-route` or not.

And I gave up finally.

If you can make a fix that works on all clients, please feel free to open a PR.
