### ISSUE TITLE
Enhance performance by BBR 

### ISSUE THREAD

**Issue by carmineyiu** [aminvakil/docker-ocserv#11]
My internet access is 500Mb/s up/down. 
With single client, CPU is less than 1 %, Memory is 2MB, but experience slow transfer rate.  After restarted docker, the performance seems improve a little. 

Some people claim there is performance improvement when BBR enable, will you add BBR to the Docker image?
https://www.linuxbabe.com/ubuntu/enable-google-tcp-bbr-ubuntu

**Comment by aminvakil** [comment]
TCP Congestion Control Algorithms are being handled by your kernel which is irrelevant to this docker.

**Comment by carmineyiu** [comment]
Yes. should be handled by kernel. At 1st, i think enable it inside docker image, so it does not affect Docker host, but seems there is no TCP stack in docker itself, I will try to enable in OMV.
