### ISSUE TITLE
how can i use my route file and private key outsite the docker ?

### ISSUE THREAD

**Issue by fengzhao** [aminvakil/docker-ocserv#3]
I want use  a TLS Certificate from Let’s Encrypt and my personal config file ，can you mount the config file and the key file outside the docker ?

**Comment by aminvakil** [comment]
You can mount a volume from host to `/etc/ocserv`, and put your own customized `ocserv.conf` there, also put your certificates there (in a `certs` folder for example) and change your `ocserv.conf` like this:
```
server-cert = /etc/ocserv/certs/fullchain.pem
server-key = /etc/ocserv/certs/key.pem
```

**Comment by carmineyiu** [comment]
Can I achieve this by docker-compose.yml ?
version '3'
services:
  app:
    image: quay.io/aminvakil/ocserv
    ports:
      - 4443:443
    volumes:
      - /etc/ocserv:/etc/ocserv:ro
    
Where in host /etc/ocserv has ocserv.conf + a folder certs contain let's Encrypt + private key?

**Comment by aminvakil** [comment]
> Can I achieve this by docker-compose.yml ?

Yes. But you should probably change this a bit.
```
version: '3.8'
services:
  ocserv:
    image: quay.io/aminvakil/ocserv
    ports:
      - 4443:443/udp
      - 4443:443
    volumes:
      - "./ocserv:/etc/ocserv"
```

> Where in host /etc/ocserv has ocserv.conf + a folder certs contain let's Encrypt + private key?

Exactly in root of `/etc/ocserv` there is a file called `ocserv.conf`.

By default a certificate will be generated which you can change its generation using environment variables, but I assume you don't want this.

So you probably want to edit `ocserv.conf` as explained in https://github.com/aminvakil/docker-ocserv/issues/3#issuecomment-707610189 and change `server-cert` and `server-key` according to your needs.

You can either put certificate and private key in `/etc/ocserv` and copy them next to your `ocserv.conf` or put them in another folder and mount them separately. Whatever suits you.

**Comment by carmineyiu** [comment]
Already change server-cert and server-key path. It now an trust website. 
Working on private key. can your docker generate client.ios?
