### ISSUE TITLE
 exec: "/entrypoint.sh": permission denied: unknown.

### ISSUE THREAD

**Issue by Wendel9209** [aminvakil/docker-ocserv#52]
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": permission denied: unknown.

**Comment by aminvakil** [comment]
Are you using `quay.io/aminvakil/ocserv` or are you building this yourself?

If you're building yourself, you may have a custom umask or something which has made `docker-entrypoint.sh` file non-executable.
Make sure it has execute permission and try again.
