### ISSUE TITLE
Modify ocserv.conf to include private certification to log in. 

### ISSUE THREAD

**Issue by carmineyiu** [aminvakil/docker-ocserv#6]
We will shutdown the Docker host frequency, really do not want to log in and manually change all parameter, 
can we volume the whole /etc/ocserv ? so we can modify ocserv.conf in the host and reload new parameter during restart?

**Comment by aminvakil** [comment]
> We will shutdown the Docker host frequency, really do not want to log in and manually change all parameter,
> can we volume the whole /etc/ocserv ?

Yes.

> so we can modify ocserv.conf in the host and reload new parameter during restart?

Yes.

Take a look at this for example: https://github.com/aminvakil/docker-ocserv/blob/master/docker-compose.yml

**Comment by carmineyiu** [comment]
I use an OMV dockerstarter.. which seems the version is too old to support sysctls
docker-compose -version
docker-compose version 1.21.0, build unknown

ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for ocserv: 'sysctls'

**Comment by aminvakil** [comment]
I don't know about OMV dockerstarter, but your docker-compose is too old, (https://github.com/docker/compose/releases/tag/1.21.0) almost three years ago.

I suggest upgrade it to latest version, but you can of course remove the sysctl part, it's not mandatory.

**Comment by carmineyiu** [comment]
remove the sysctl part, log error with following
sysctl: error setting key 'net.ipv4.ip_forward': Read-only file system

  ocserv:
    image: quay.io/aminvakil/ocserv
    restart: unless-stopped
    container_name: ocserv
    hostname: www.example.com
    ports:
      - 443:443/udp
      - 443:443
    volumes:
      - "/etc/ocserv:/etc/ocserv:rw"
    cap_add:
    - NET_ADMIN
    security_opt:
    - no-new-privileges

**Comment by aminvakil** [comment]
That's fine.
You should enable `net.ipv4.ip_forward` on host using this command:
`sysctl net.ipv4.ip_forward=1`

To make it permanent add `net.ipv4.ip_forward = 1` to `/etc/sysctl.conf`. You can find out more by searching `sysctl net.ipv4.ip_forward`.

**Comment by aminvakil** [comment]
Sorry, I was wrong, it is mandatory.
You should either enable it using `sysctl` in docker-compose or enable it manually from host.
Search `sysctl net.ipv4.ip_forward=1` and see how you can make it permanent.

**Comment by carmineyiu** [comment]
tks, it work. 
Had not set sysctl net.ipv4.ip_forward=1

**Comment by aminvakil** [comment]
You're welcome.

Feel free to add a PR mentioning this issue.
