### ISSUE TITLE
ocserv-web

### ISSUE THREAD

**Issue by ShamanIEA** [aminvakil/docker-ocserv#79]
Dear aminvakil.
I apologize for my English.
Tell me, do you have docker for the ocserv-web web interface and is it planned to appear in the near future?

Since I'm new to Linux and I don't have good command line skills, having a web interface will help a lot in checking its performance.
Your application is very well assembled in docker, but I haven't figured out yet whether it works or not, and I can't figure out how to create clients on the command line.
And how to check the functionality of the application in docker

**Comment by aminvakil** [comment]
No unfortunately, you ought to learn the basics of docker and linux commands.
