### ISSUE TITLE
private ip address

### ISSUE THREAD

**Issue by carmineyiu** [aminvakil/docker-ocserv#8]
The IP address pool 192.168.99.X is very common used. can you change it to 10.10.x.x  which rarely use by home router

**Comment by aminvakil** [comment]
That's opinion based, in Iran where I live internal network of country is using exactly 10.10.x.x for certain purposes.

Although they should not do this, but changing to 10.10.x.x would break many stuff for myself.

Also anyone can change to whatever subnet more appropriate if they want.
